### ISSUE TITLE
Being able to add #hashtags would be great.

### ISSUE THREAD

**Issue by VivekatYashaa** [10up/autoshare-for-twitter#118]
**Is your enhancement related to a problem? Please describe.**
No current issues but being able to add a custom #hashtags along with #hostwebsite hashtag, #category would be great.

**Describe the solution you'd like**
No current issues but being able to add a custom #hashtags along with #hostwebsite hashtag, #category would be great.

**Designs**

- Settings Section
- Custom Hashtag list
- Hashtag Sequence  (#category, #Website #Custom1, #Custom2)

**Describe alternatives you've considered**
No alternatives available

**Additional context**
Thank you

**Comment by jeffpaul** [comment]
@VivekatYashaa welcome to Autoshare for Twitter and thanks for the feedback!  We have issue #66 that covers the feature request for hashtags, so please subscribe to updates on that issue and add any additional thoughts you have on functionality there... thanks!
