### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by rickalee** [10up/autoshare-for-twitter#119]
Hi team,

For VIP Go Compatability come February 23rd - we need to update and test against the latest version of https://github.com/abraham/twitteroauth/ 

https://github.com/10up/autoshare-for-twitter/blob/develop/composer.json#L17

The PHP 7.4 issue 
vendor/abraham/twitteroauth/src/SignatureMethod.php

```
Line 61

 $result |= ord($built{$i}) ^ ord($signature{$i}); 
```

**Comment by jeffpaul** [comment]
@rickalee looks like we're pulling in:
https://github.com/10up/autoshare-for-twitter/blob/1e45556e49cb22b9ec1053de14060bda77ed7529/composer.json#L17

and most current is [2.0.1](https://github.com/abraham/twitteroauth/releases/tag/2.0.1).  Is there a sense of whether we need/should bump all the way to 2.0.1 or some intermediate version?

**Comment by rickalee** [comment]
@jeffpaul Based on the note from [1.0.0](https://github.com/abraham/twitteroauth/releases/tag/1.0.0) around PHP version support, I think https://github.com/abraham/twitteroauth/releases/tag/1.2.0 would be the best version to try first.

**Comment by thrijith** [comment]
Hi @jeffpaul, if this is available, I can take a look.

**Comment by jeffpaul** [comment]
@thrijith go for it, thanks!

**Comment by thrijith** [comment]
- Tested the version `1.2.0` on PHP version `7.4.13`, have tested out tweet without and with featured image, seems to be working as expected, please let me know if any other test need to be done, thanks!

- Tweets demo: https://twitter.com/gh_issue_help

- Did a compatibility test for PHP version `7.0` which is the current required version set in plugin, [here](https://gist.github.com/thrijith/cc546d2dc47e0dbbb96a6beebc6f9e4d) are the results.

- Based on https://github.com/abraham/twitteroauth/releases/tag/1.0.0 and above compatibility sniff results, we would need to update required PHP version as 7.2 in plugin.


cc: @jeffpaul @rickalee

**Comment by jeffpaul** [comment]
@thrijith sounds good.  Want to craft a PR to handle the `twitteroauth` and PHP bumps?

**Comment by thrijith** [comment]
@jeffpaul Sure!
