### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#133]
**Is your enhancement related to a problem? Please describe.**
 Once WordPress 5.8 is released, we'll want to test Autoshare for Twitter to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Autoshare for Twitter on WordPress 5.8
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: #92, #110.

**Comment by barneyjeffries** [comment]
@jeffpaul  I have finished testing against WP 5.8 and not found any issues. I have created a PR here https://github.com/10up/autoshare-for-twitter/pull/135 for the "tested to" change.
