### ISSUE TITLE
Add Hashtags or custom post style

### ISSUE THREAD

**Issue by arkfrance** [10up/autoshare-for-twitter#139]
**Is your enhancement related to a problem? Please describe.**

No, it's only to make the app better

**Describe the solution you'd like**

I suggest to add a Hashtag field in the admin backend to auto add them to the posts.

**Comment by jeffpaul** [comment]
@arkfrance I'm closing this in favor of #66 as a previous request to add this sort of support.  Please subscribe to that issue for future updates and add any additional thoughts you have on how it would ideally work there... thanks!
