### ISSUE TITLE
Publish after save draft with tweet enabled in Classic Editor always tweet post.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/autoshare-for-twitter#168]
### Describe the bug

I came across this issue during working on E2E tests(#158).

Currently, whenever we `Save draft` post with `Tweet this post` checkbox checked, it always tweets post when we publish a post, even when we publish a post with the `Tweet this post` checkbox unchecked. Also, is not possible to uncheck the checkbox, if we uncheck the checkbox and `Save draft` then it gets checked again. (please check the attached screen recording for more idea on this). However, direct publish with the `Tweet this post` checkbox unchecked working fine.

This is happening with classic editor only, tweet functionality working fine with Block editor.

### Steps to Reproduce
1. Install the Classic Editor plugin.
2. Create a draft post in classic editor (make sure the `Tweet this post` checkbox is checked)
3. Try to uncheck the checkbox and `Save draft`
4. Notice checkbox is still checked even after saving.
5. Uncheck the checkbox and `Publish` post.
6. See post is tweeted, it shouldn't tweet when the checkbox is unchecked.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/10613171/171558505-862bcdb5-b3ae-4b33-a03d-353ebfc61294.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Whoa, nice catch and fix there @iamdharmesh, thank you!
