### ISSUE TITLE
Check if plugin can work with only Essential access

### ISSUE THREAD

**Issue by iamdharmesh** [10up/autoshare-for-twitter#173]
### Is your enhancement related to a problem? Please describe.

For now, the plugin requires Elevated access to Twitter API. Elevated access is required maily for upload media which is not available under Twitter API 2.

Recently, Twitter has announced that V1.1 media endpoints will be available under Essential access. more info: https://twittercommunity.com/t/v1-1-media-endpoints-available-for-essential-access-in-the-twitter-api-v2/171664

 The user has to apply for Elevated access from the developer portal and after getting approval from the Twitter team they can use API credentials. This issue is created to check on upload media functionality and make sure all working fine with `Essential access`. If all is working as expected we can remove setup steps from settings related to requesting Elevated access, which will make user onboarding simple.

### Describe alternatives you've considered

Keep it as it is.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@thrijith FYI on an issue we can track against for any research you're doing on this 🙏🏼

**Comment by jeffpaul** [comment]
This issue has elevated importance now with the pending Twitter action to revoke free access to the v2 and v1.1 APIs (see https://twitter.com/twitterdev/status/1621026986784337922).  While we investigate (1) whether we can continue to support a free Twitter API integration option, (2) whether we need to update to support a paid-only Twitter API integration, (3) or some combination of free/paid integrations we should look into a patch release that adds a dismissable notification that any issues with the plugin starting on February 9th, 2023 are likely due to Twitter API changes (and link to the TwitterDev tweet link).

**Comment by jeffpaul** [comment]
Also, as @thrijith noted we'll likely want to consider any updates needed to tests here as well (e.g., https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/cypress.yml#L69-L73).

**Comment by iamdharmesh** [comment]
**Update related to Essential Access:** Currently, the plugin uses API version v1.1 which requires Elevated access, We can update the plugin to use API v2 to make it work with Essential access (As media upload API of v1.1 is working with Essential access). However, as per note here https://developer.twitter.com/en/docs/twitter-api/migrate/ready-to-migrate existing Apps
(created before November 15th, 2021) will need to attach to a Project. Need to check more on how old apps can be used to use API v2. 

![Screenshot 2023-02-07 at 9 55 15 PM](https://user-images.githubusercontent.com/10613171/217304022-ab58e70b-8a63-40d6-9f72-d1899d8c6edb.png)

Thanks

**Comment by iamdharmesh** [comment]
I just noticed one update in the Access level table, the price is updated to **TBD**, earlier it was **Free**. (see screenshot and link below). So, Maybe access levels and other API-related stuff will remain the same and some pricing will be applied to each level. 

**[03 Feb:](https://web.archive.org/web/20230203154151/https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api)** [Link for web.archive.org](https://web.archive.org/web/20230203154151/https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api)
![image](https://user-images.githubusercontent.com/10613171/217574851-162216be-7b05-44cd-8102-2bc0fb492618.png)


**[Today:](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-level)**
![image](https://user-images.githubusercontent.com/10613171/217574392-614432c0-f0fa-461d-ae4b-f89e35bf8998.png)

**Comment by jeffpaul** [comment]
[TwitterDev noted on February 8th that starting today](https://twitter.com/TwitterDev/status/1623467618400374784):
> A new form of free access will be introduced as this is extremely important to our ecosystem – limited to Tweet creation of up to 1,500 Tweets per month for a single authenticated user token, including Login with Twitter.

As of now, there's no update from them ([on Twitter](https://twitter.com/TwitterDev) or [on their developer docs site](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-level) either).  I'll continue to monitor and update here when we see a confirmed free tier for us to test against and see if existing plugin functionality will still function and then we can decide on how best to proceed then.

**Comment by jeffpaul** [comment]
Also, based on [March 29th](https://twitter.com/TwitterDev/status/1641222786894135296) and [April 20th](https://twitter.com/TwitterDev/status/1649191520250245121) tweets from Twitter Dev it sounds like all API tiers prior to v2 as well as any v2 tiers that are not explicitly named "Free" or "Paid" will be deprecated by April 29th.  Whether that's a hard deprecation, whether that date holds, or any other changes from Twitter are hard to assess, it seems like we need to plan for a path forward of Autoshare for Twitter users that will (1) need to upgrade their Twitter API account to a v2 Free or Paid account and (2) the plugin will need to update set up instructions for the v2 process as well as how folks can migrate from v1* to v2.

Given the 10up company meetup next week, I do not expect these changes to be ready or released until much later in May.  Should someone have the ability to help research needs on these two changes, then please share here / welcome a PR to help... thanks!
