### ISSUE TITLE
Improve override Tweet message.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/autoshare-for-twitter#178]
### Is your enhancement related to a problem? Please describe.

Sub-task of https://github.com/10up/autoshare-for-twitter/issues/59

**2. Improve edit Tweet message.**
 - [ ] ~~Full Tweet message is always shown - enabling different editors to edit the message before (or after) publishing~~
 - [x] Short warning when message getting long
 - [x] Error when message is too long
 - [x] Set max character for the text area, so that people can't enter longer Tweets

### Designs

Enabled state: 
![Screen Shot 2019-12-18 at 10 30 03 PM](https://user-images.githubusercontent.com/2818133/71145100-f6cbcc00-21e5-11ea-8349-023e64dc78f1.png)

Enabled - length warning: 
![Screen Shot 2019-12-18 at 10 30 30 PM](https://user-images.githubusercontent.com/2818133/71145120-05b27e80-21e6-11ea-9dfc-41edeeb32705.png)

Enabled - length error: 
![Screen Shot 2019-12-18 at 10 30 58 PM](https://user-images.githubusercontent.com/2818133/71145138-182cb800-21e6-11ea-9143-045ac3baf8d8.png)

Enabled - with featured image: 
![Screen Shot 2019-12-18 at 10 31 27 PM](https://user-images.githubusercontent.com/2818133/71145158-28dd2e00-21e6-11ea-94fa-58916f6de27d.png)

Enabled - featured image removed: 
![Screen Shot 2019-12-18 at 10 31 55 PM](https://user-images.githubusercontent.com/2818133/71145175-385c7700-21e6-11ea-97b1-0ccfa5243d67.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
> Full Tweet message is always shown - enabling different editors to edit the message before (or after) publishing

@jeffpaul, I have discussed this feature with @Sidsector9 and we feel that the current UX is better and allows editing the message only when needed. Also, I believe the value added by this feature to the plugin is not worth the effort required to implement this (Considering the plugin is on stable support). 

|Current UI (Normal) | Current UI (After click Edit)|
|---|---|
|![image](https://user-images.githubusercontent.com/10613171/208106391-9a13efaf-412d-46ed-bb5a-c53a9ad4eea7.png)|![image](https://user-images.githubusercontent.com/10613171/208107635-18a98b53-cd66-45f7-ae15-fbedeab3a8ee.png)|

However, we can still work below improvements which looks like a great addition to the plugin.
- Short warning when message getting long
- Error when message is too long
- Set max character for the text area, so that people can't enter longer Tweets

Please let me know what do you think about this.

Thanks

**Comment by jeffpaul** [comment]
@iamdharmesh I concur with your assessment, thanks for the detailed comment!
