### ISSUE TITLE
[AutoTweet Panel]  Add "Tweet now" functionality.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/autoshare-for-twitter#181]
### Is your enhancement related to a problem? Please describe.

Sub-task of #59 

**[AutoTweet Panel]  Add "Tweet now" functionality.**
- [ ] A post can be Tweeted multiple times after publishing - even by a different editor
- [ ] Tweet now will expose controls and allow instant Tweeting
- [ ] Message and settings should persist to allow multi-editor or dedicated social media person workflow

### Designs

Published - Tweeted: 
![Screen Shot 2019-12-18 at 10 33 48 PM](https://user-images.githubusercontent.com/2818133/71145232-7ce81280-21e6-11ea-8df7-1ded50217a69.png)

Published - Tweet now: 
![Screen Shot 2019-12-18 at 10 34 35 PM](https://user-images.githubusercontent.com/2818133/71145256-98531d80-21e6-11ea-863f-0fbfddd6054d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
@iamdharmesh I worked on this and I have a suggestion.

The Post-publish panel appears once, only when the post is published. I doesn't ever appear again. So adding the "Tweet now" feature there wouldn't make sense.

A good place to add this would be the AutoTweet panel. This appears when you open a post that is successfully tweeted.

Let me know your thoughts on this.

**Comment by iamdharmesh** [comment]
Hi @Sidsector9, Thanks for pointing this out. You are correct, the "Tweet now" feature should be in Auto Tweet Panel.
