### ISSUE TITLE
Add PHP Unit tests [4 hrs.]

### ISSUE THREAD

**Issue by adamsilverstein** [10up/autoshare-for-twitter#20]
Depends on https://github.com/10up/10up-auto-tweet/issues/16

**Comment by thrijith** [comment]
Hi @jeffpaul, I'd like to take this if available, thanks!

**Comment by thrijith** [comment]
Hi @jeffpaul, I see there are tests already setup for most of the files, https://github.com/10up/autoshare-for-twitter/tree/develop/tests/phpunit, just want to make sure the change required is to add / update tests to include anything that was missed. I've started on this so far added tests to check hooks are properly added and other minor changes.

**Comment by jeffpaul** [comment]
@thrijith that sounds perfect, yes please and thanks!
