### ISSUE TITLE
Unable to activate on existing installation

### ISSUE THREAD

**Issue by jennsuzhoy** [10up/autoshare-for-twitter#227]
### Describe the bug

We've noticed the plugin is no longer active and no longer able to activate on our multisite. Initial investigation showed an old version in use, but the issue persists after updating to the latest version in Dev environments.

### Steps to Reproduce

1. Noticed new posts are no longer auto-tweeting
2. Check Plugins tab
3. Note plugin is inactive
4. Note "activate" option missing

### Screenshots, screen recording, code snippet

![chrome-capture-2023-3-3](https://user-images.githubusercontent.com/11678742/229579463-3027895a-f919-4cbd-ac66-b1eef7958f38.png)
![chrome-capture-2023-3-3 (1)](https://user-images.githubusercontent.com/11678742/229579714-de931458-a280-4d64-b345-faa93c5bd1e2.png)

### Environment information

Lenovo ThinkPad
Windows 11 Enterprise
Version	22H2
Installed on	‎9/‎20/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

### WordPress information

`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: -07:00
permalink: /blog/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 14186
site_count: 10
network_count: 1
dotorg_communication: true

### wp-dropins (3) ###

advanced-cache.php: true
db-error.php: true
object-cache.php: true

### wp-active-theme ###

name: Microsoft Stories (microsoft-stories-theme)
version: 1.0
author: Modern Tribe, Inc.
author_website: http://tri.be
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, title-tag, html5, editor-style, menus
theme_path: /nas/content/live/winblogsprod/wp-content/themes/microsoft-stories-theme
auto_update: Disabled

### wp-themes-inactive (1) ###

Windows Blogs: version: 0.2.6, author: 10up, Auto-updates disabled

### wp-mu-plugins (15) ###

curated-posts-cache-expiration.php: author: (undefined), version: (undefined)
Force Plugin Activation/Deactivation: version: 1.0, author: Modern Tribe
Force Strong Passwords - WPE Edition: version: 1.8.0, author: Jason Cosper
login-styles.php: author: (undefined), version: (undefined)
make-cookies-secure.php: author: (undefined), version: (undefined)
ms-redirects.php: author: (undefined), version: (undefined)
override-comment-reporting.php: author: (undefined), version: (undefined)
prevent-rest-access.php: author: (undefined), version: (undefined)
Tribe Multisite Large Network: version: 1.0, author: Modern Tribe
Tribe Security Measures: version: 1.0, author: Modern Tribe
wp-seo-scraper-fix.php: author: (undefined), version: (undefined)
WP Engine Cache Plugin: version: 1.1.2, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.6.0, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 5.0.1, author: WP Engine

### wp-plugins-active (37) ###

Advanced Custom Fields PRO: version: 5.12.2, author: Delicious Brains (latest version: 6.0.7), Auto-updates disabled
AMP: version: 2.1.4, author: AMP Project Contributors (latest version: 2.4.1), Auto-updates disabled
Animated Post Thumbnails: version: 0.1.0, author: 10up, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors (latest version: 1.6.3), Auto-updates disabled
CMB2: version: 2.10.1, author: CMB2 team, Auto-updates disabled
Co-Authors Plus: version: 3.5.2, author: Mohammad Jangda, Daniel Bachhuber, Automattic (latest version: 3.5.10), Auto-updates disabled
CodeStyling Localization Preserver: version: 1.0.6, author: Sowmedia.nl (Steve Lock), Auto-updates disabled
Dynamic Asset Versioning: version: 0.1.0, author: Growella, Auto-updates disabled
Fix Instagram oEmbed: version: 1.0.0, author: 10up, Auto-updates disabled
GistPress: version: 3.0.2, author: Blazer Six, Auto-updates disabled
Microsoft 1DS Metrics: version: 1.0.0, author: Modern Tribe, Auto-updates disabled
Microsoft ACF Fabric Icon Field THING: version: 1.0, author: Microsoft, Auto-updates disabled
Microsoft Clarity: version: 1.0.0, author: Modern Tribe, Auto-updates disabled
Microsoft Google Tag Manager: version: 0.0.5, author: Jenn Soloway, Auto-updates disabled
Microsoft JSON Filters: version: 1.0, author: 10up, Auto-updates disabled
Microsoft Pixels: author: (undefined), version: (undefined), Auto-updates disabled
Microsoft Stories Core Functionality: version: 1.0, author: Modern Tribe, Auto-updates disabled
Microsoft UHF: version: 0.3.8, author: 10up, Auto-updates disabled
Microsoft User Badges: version: 0.1.0, author: WebDevStudios, Auto-updates disabled
Multiple Post Thumbnails: version: 1.7, author: Chris Scott, Auto-updates disabled
Multisite Enhancements: version: 1.6.1, author: Frank Bültge, Auto-updates disabled
Page Links To: version: 3.3.6, author: Mark Jaquith, Auto-updates disabled
Post Finder: version: 0.2, author: Micah Ernst, Auto-updates disabled
Post Meta Revisions: version: 1.0.0, author: Adam Silverstein - code developed with others, Auto-updates disabled
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond), Auto-updates disabled
Safe Redirect Manager: version: 1.10.1, author: 10up (latest version: 1.11.1), Auto-updates disabled
Safe Report Comments: version: 0.4.1, author: Thorsten Ott, Daniel Bachhuber, Automattic, Auto-updates disabled
SearchWP: version: 4.2.2, author: SearchWP (latest version: 4.2.9), Auto-updates disabled
Simple Local Avatars: version: 2.2.0, author: Jake Goldman, 10up (latest version: 2.7.4), Auto-updates disabled
Tribe Panel Builder: version: 3.4, author: Modern Tribe, Inc., Auto-updates disabled
Tribe Storage: version: 2.5.5, author: Modern Tribe, Auto-updates disabled
User Switching: version: 1.5.8, author: John Blackbourn & contributors (latest version: 1.7.0), Auto-updates disabled
Windows Blogs Aggregator: version: 0.2.1, author: 10up, Auto-updates disabled
Windows Blogs Azure GUID: version: 0.1.0, author: 10up, Auto-updates disabled
Windows Blogs Popular Posts: version: 0.1, author: 10up, Auto-updates disabled
WP Term Images: version: 1.0.0, author: John James Jacoby, Auto-updates disabled
Yoast SEO: version: 18.8, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (22) ###

Autoshare for Twitter: version: 1.0.6, author: 10up (latest version: 1.3.0), Auto-updates disabled
Classic Editor Addon: version: 3.0.1, author: <a href="https://so-wp.com">Pieter Bos</a>, <a href="https://gschoppe.com">Greg Schoppe</a> (latest version: 4.2.0), Auto-updates disabled
Classic Widgets for WP: version: 0.1, author: DigitalDyna, Auto-updates disabled
CodeStyling Localization: version: 1.99.30, author: Heiko Rabe, Auto-updates disabled
Content Blocks: version: 1.1.4, author: Eric Mann, Ivan Lopez, Brian Watson, Auto-updates disabled
Enlighter - Customizable Syntax Highlighter: version: 4.4.2, author: Andi Dittrich, Auto-updates disabled
Instant Articles for WP: version: 4.2.1, author: Automattic, Dekode, Facebook (latest version: 5.0.2), Auto-updates disabled
Jetpack by WordPress.com: version: 9.7.1, author: Automattic, Auto-updates disabled
Jobs Blog Migration Tool: version: 0.0.1, author: 10up, Auto-updates disabled
Liveblog: version: 1.9.6, author: WordPress.com VIP, Big Bite Creative and contributors, Auto-updates disabled
Microsoft Metrics: version: 1.0.0, author: 10up, Auto-updates disabled
Microsoft Require Alt Tags: version: 0.1.2, author: 10up, Auto-updates disabled
Public Post Preview: version: 2.9.3, author: Dominik Schilling (latest version: 2.10.0), Auto-updates disabled
Query Monitor: version: 3.7.1, author: John Blackbourn (latest version: 3.12.1), Auto-updates disabled
Restricted Site Access: version: 7.2.0, author: Jake Goldman, 10up, Oomph (latest version: 7.3.5), Auto-updates disabled
Social Login: version: 5.7, author: OneAll Social Login <support@oneall.com>, Auto-updates disabled
Stream: version: 3.8.2, author: XWP (latest version: 3.9.2), Auto-updates disabled
Two Factor Authenticator: version: 0.48, author: 10up, Henrik Schack, Auto-updates disabled
Windows Blogs Lockdown: version: 0.1, author: 10up, Auto-updates disabled
Windows Blogs Twitter Tracking: version: 0.1, author: 10up, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg (latest version: 0.8), Auto-updates disabled
Yoast Test Helper: version: 1.16, author: Team Yoast (latest version: 1.17), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-1094-azure x86_64
httpd_software: nginx
php_version: 7.4.33.2 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 43300
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.40-43-log
client_version: mysqlnd 7.4.33.2
max_allowed_packet: 16777216
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/winblogsprod/wp-content
WP_PLUGIN_DIR: /nas/content/live/winblogsprod/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: not writable
plugins: writable
themes: writable
mu-plugins: writable

### amp_wp ###

amp_slug_query_var: amp
amp_slug_defined_late: false
amp_mode_enabled: reader
amp_reader_theme: legacy
amp_templates_enabled: post
amp_serve_all_templates: This option does not apply to Reader mode.
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: undefined
amp_css_transient_caching_time_series: 
amp_libxml_version: 2.9.13

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@jennsuzhoy we've recently released v2 of the plugin that better supports the Twitter v2 API... could you try and see if this new version activates as expected for you?
