### ISSUE TITLE
Add a plugin release command/process

### ISSUE THREAD

**Issue by adamsilverstein** [10up/autoshare-for-twitter#26]
The plugin `release` command should:
* Prepare the plugin for distribution, creating a release folder that contains only the files needed to run the plugin.
* Include only vendor dependencies used in the plugin.
* The `release-zip` command should prepare a plugin zip ready for uploading.

**Comment by jeffpaul** [comment]
The [GitHub Action](https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/deploy-to-wpdotorg.yml) and [release instructions](https://github.com/10up/autoshare-for-twitter/blob/develop/CONTRIBUTING.md#release-instructions) seem to cover this pretty well.  The only additional item that would be nice is https://github.com/10up/action-wordpress-plugin-deploy/issues/4 as adding a ZIP file to GitHub releases would get us some metrics on downloads of plugin versions from GitHub (to go along with .ORG download metrics).

**Comment by jeffpaul** [comment]
The latest commits in #105 should suffice for me on this, so I'll tie this issue to that PR.
