### ISSUE TITLE
Auto Sharing is not working

### ISSUE THREAD

**Issue by waqas7074** [10up/autoshare-for-twitter#262]
### Describe your question

By using this plugin post is not sharing automatically.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@waqas7074 can you provide a Site Health Info export of your site so we can try to replicate your setup and see what's going wrong?  Also, do you have any error messages on the plugin settings page or after publishing posts?
