### ISSUE TITLE
"Could not authenticate you."

### ISSUE THREAD

**Issue by nathanshumate** [10up/autoshare-for-twitter#278]
### Describe your question

Pressing the "Connect Twitter account" results in the error message "Could not authenticate you.", with no further information. Help?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @nathanshumate, 

Thank you for reporting the issue.

As the error indicates, it seems that something is misconfigured between the plugin and Twitter. There are a few potential reasons for this:

**1. Incorrect Twitter API credentials:** Please ensure that you have entered the correct Twitter API credentials.

**2. Deprecated access levels:** If you are still using the old Twitter access levels (Standard (v1.1), Essential (v2), Elevated (v2), etc...), you must migrate to the new access levels (Free, Basic, Pro, etc.). Please make sure to migrate to the new access levels to ensure uninterrupted functionality. Here’s how you can do it:
```
1. Go to the following URL: https://developer.twitter.com/en/portal/products
2. Look for the "Downgrade" button.
3. Click on it to migrate to the free access level.
```
**3. The Twitter Developer App is not configured correctly:** (Please confirm by following the steps below)
- Go to the [Twitter developer portal](https://developer.twitter.com/en/portal/dashboard)
- Click on Projects & Apps on the left navigation menu.
- Find the App and click it to show the Settings page for the App.
- Click "Setup" under User authentication settings to setup Authentication.
- Enable `OAuth 1.0a` and Set App permissions to **Read and write**.
- Set the Website URL to `YOUR_WEBSITE_URL`.
- Set the Callback URLs fields to `YOUR_WEBSITE_URL/wp-admin/admin-post.php?action=authoshare_authorize_callback` and click Save.
- Switch from the "Settings" tab to the "Keys and tokens" tab.
- Click on the `Generate`/`Regenerate` button in the `Consumer Keys` section.
- Copy the `API Key` and `API Key Secret` values and save them in plugin settings.


Please let me know if you are still facing the issue after checking all of this.

Thank you.

**Comment by nathanshumate** [comment]
Well, I don't know which part of it I had wrong, but I went through all the steps again and this time it worked. Thanks for your help!

**Comment by iamdharmesh** [comment]
@nathanshumate Glad to know that it worked. Please feel free to report if you face any issues in the future.
