### ISSUE TITLE
How to auto tweet when using wp_insert_post to programmatically add a post?

### ISSUE THREAD

**Issue by meyer744** [10up/autoshare-for-twitter#283]
### Describe your question

I am adding posts using wp_insert_post() and they are not tweeted. I have to change status manually back to draft and then to published. I have also tried inserting as draft and then using wp_update_post() to switch to 'publish' and also using wp_publish_post() to switch to published, neither of which have worked. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @meyer744,

Thank you for bringing up a question.

Could you please try publishing the post after adding the "Autoshare for Twitter" post metadata? Autoshare for Twitter uses the following metadata:

- `autoshare_autoshare_for_twitter`: To enable/disable tweeting on post.
- `autoshare_tweet-allow-image` - To include the featured image in the Tweet.
- `autoshare_tweet-body` : To set a custom tweet message.
- `autoshare_tweet_accounts` - To specify the Twitter accounts for sending tweets.

A sample code snippet should look something like this:
```php
// Create a new post.
$post_id = wp_insert_post(
	array(
		'post_title'  => 'Test Title',
		'post_status' => 'draft',
	)
);

// Enable Tweet on post.
update_post_meta( $post_id, 'autoshare_autoshare_for_twitter', 1 );
// Include feature image in the tweet.
update_post_meta( $post_id, 'autoshare_tweet-allow-image', 'yes' );
// Specify the Twitter accounts for sending tweets.
update_post_meta( $post_id, 'autoshare_tweet_accounts', array( "TWITTER_ACCOUNT_ID" ) );

// Publish the post.
wp_publish_post( $post_id );
```

Please let us know if this doesn't work for you or if there's anything else we can assist you with!

Thank you.
