### ISSUE TITLE
auto sharing not working

### ISSUE THREAD

**Issue by Sreejith00000** [10up/autoshare-for-twitter#286]
### Describe your question

every post, need to go edit, and tweet manually from the post editor. help pls. settings are all fine. double, tripple checked!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@Sreejith00000 can you please confirm details from your Site Health Info export so we can try and replicate your setup?  Can you also confirm some details from your Twitter configuration from the Autoshare for Twitter settings in case something's malformed there?

**Comment by Sreejith00000** [comment]
Pls find attachments .

Attached Twitter developer settings screen shot and

Screenshots of Autoshare plugin setup settings in wordpress.

Already the ensured and double checked the settings. Although, if I publish
manually from wordpress, it is working. But posts aren't getting
"auto"published in twitter. Only manual.

**Comment by Sreejith00000** [comment]
![1](https://github.com/10up/autoshare-for-twitter/assets/112242809/1835e25d-dd26-4605-ad9b-5c78c0b4ea32)
![posts in wordpress not autoshared](https://github.com/10up/autoshare-for-twitter/assets/112242809/c276731f-4af4-446d-b2bc-f0fe56081627)
[notShared.webm](https://github.com/10up/autoshare-for-twitter/assets/112242809/e095e306-221a-4a92-b3e1-5f11c2861df1)

**Comment by iamdharmesh** [comment]
This looks related to #287

**Comment by Sreejith00000** [comment]
I have deleted the plugin
