### ISSUE TITLE
WP Automatic posts not autoshared

### ISSUE THREAD

**Issue by sunnmagic** [10up/autoshare-for-twitter#287]
### Describe your question

Hi,

I'm using "WordPress Automatic" to automatically create posts, but in this case, they are not shared on Twitter. Is there a way to make it work?

Regards,
Mikael

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@sunnmagic can you share a link to that plugin so we can try and replicate your issue to see where a fix might be needed?

**Comment by sunnmagic** [comment]
Sure: https://codecanyon.net/item/wordpress-automatic-plugin/1904470 :)
