### ISSUE TITLE
Autopost, formerly X, is not posting from website to X

### ISSUE THREAD

**Issue by demwaves** [10up/autoshare-for-twitter#303]
### Describe the bug

Autopost, formerly X, is not posting from website to X.

This is although the Autopost app has been installed and configured on both the website and X

### Steps to Reproduce

Autopost, formerly X, is not posting from website to X.

This is although the Autopost app has been installed and configured on both the website and X

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @demwaves,

Thank you for reporting the issue. Could you please provide more information and detailed reproduction steps for the problem you are facing? Are you encountering any error messages? If so, could you please provide them?

Thanks.
