### ISSUE TITLE
Autopost to x won't connect

### ISSUE THREAD

**Issue by glensidecross** [10up/autoshare-for-twitter#305]
### Describe the bug

I have gone through the setup process including generating keys and saving. Everything looks good up to that point, but when I hit the connect button, it takes me to X and when it redirects back to the plugin page - it still shows as no account connected.

### Steps to Reproduce

Go through the setup process and then hit the connect button. It will redirect back to the plugin page seemingly succesfully, but the plugin shows no account connected.

### Environment information

Windows 11.

### WordPress information

Most recent wordpress.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@glensidecross are you utilizing the API v2 credentials from X?

**Comment by biondlll** [comment]
I have the similiar issue. Twitter requires both 1.0a and 2.0 as noted in the screen shot. The plug in only reqeusts keys for 1.0a. Please advise. 
![image](https://github.com/10up/autoshare-for-twitter/assets/158245253/b5e282c8-f166-4d1c-8dfc-a9c10a6c4dd3)

**Comment by johnnychrome** [comment]
I am having the same issue (new user here). I tried both the 1.0a credentials and the 2.0 (just in case!). Everything looks hunky-dory, but it fails on click clicking the Connect X/Twitter button.

<img width="1072" alt="Screenshot 2024-02-16 at 8 45 11 AM" src="https://github.com/10up/autoshare-for-twitter/assets/127689690/d0ec9473-0cee-4382-a298-da3b24132426">

**Comment by johnnychrome** [comment]
> I am having the same issue (new user here). I tried both the 1.0a credentials and the 2.0 (just in case!). Everything looks hunky-dory, but it fails on click clicking the Connect X/Twitter button.
> 
> <img alt="Screenshot 2024-02-16 at 8 45 11 AM" width="1072" src="https://private-user-images.githubusercontent.com/127689690/305449657-d0ec9473-0cee-4382-a298-da3b24132426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjk5ODgsIm5iZiI6MTcwODEyOTY4OCwicGF0aCI6Ii8xMjc2ODk2OTAvMzA1NDQ5NjU3LWQwZWM5NDczLTBjZWUtNDM4Mi1hMjk4LWRhM2IyNDEzMjQyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwMDI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTVjZTI0MGUxOGEwZjkyZTgwYWY1MDM1M2I0ZWQ4YmQzNzBmNDY0ZDg0MjRjYzdjMzJkNGE5YjQ3ODczZWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hog3GGfTKpKP-GQGxeUxAfvS55aqSZ8k4BzPjaURlv8">

I tried again 8 hours later, generating new keys again as a precaution, and it worked this time!

**Comment by iamdharmesh** [comment]
**Update:**

I have checked on this and I am not able to reproduce this, I have checked on the [Community forum](https://devcommunity.x.com/search?q=Could%20not%20authenticate%20you) of X but no useful findings there as well.
