### ISSUE TITLE
Error  429

### ISSUE THREAD

**Issue by srpolanco** [10up/autoshare-for-twitter#308]
### Describe your question

Good afternoon,

I would like to know why I always get this error and have to wait 24 hours or more to continue publishing. Let's see if you can tell me how to correct it please.  ---> https://prnt.sc/kPfbzZJ0xeZS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hello @srpolanco,

Thanks for opening an issue.

The error message "**429: Too Many Requests**" indicates that you have exceeded the usage limits of **X/Twitter**'s Free API access. With the Free API, you are allowed **1,500 Posts per month** and **50 requests** within a 24-hour period.

To avoid encountering this error in the future and to have higher usage limits, we recommend considering a subscription to either the Basic or Pro access level. These access levels provide increased quotas and additional benefits to accommodate your needs. For more information on X/Twitter API access levels, you can visit this link: https://developer.twitter.com/en/products/twitter-api.

You can find more information on this at FAQ [here](https://github.com/10up/autoshare-for-twitter?tab=readme-ov-file#im-encountering-the-error-message-429-too-many-requests-what-could-be-the-possible-reason-for-this-error).


Thank you.
