### ISSUE TITLE
Installation and setup

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#57]
**Is your enhancement related to a problem? Please describe.**
Better onboarding and easier setup - leading to better initial experience.  Better control on behaviour:
- Ability to define which post types will Autoshare be available on
- Configurable default ON/OFF for posts
- Ability to configure default featured image inclusion
- Ability to tweet a post multiple times

**Describe the solution you'd like**
- [ ] Prompt what the user needs to do after Activating the plugin (need to decide if Admin banner is best, necessary UX here)
- [ ] Provide step-by-step instructions
- [ ] Only show settings which are needed for initial setup
- [ ] Branding and links to more in-depth help
- [ ] Group configuration options by areas
- [ ] Only show post types when "Selected content types only" is selected
- [ ] Toggle connection settings inline

**Designs**
Activating the plugin:
![Screen Shot 2019-12-13 at 7 26 22 PM](https://user-images.githubusercontent.com/2818133/70841243-7e789b80-1dde-11ea-9033-b9960311a6d4.png)
Initial setup:
![Screen Shot 2019-12-13 at 7 28 25 PM](https://user-images.githubusercontent.com/2818133/70841275-c5669100-1dde-11ea-87de-36b212d411e6.png)
Configuration:
![Screen Shot 2019-12-13 at 7 29 37 PM](https://user-images.githubusercontent.com/2818133/70841299-ee872180-1dde-11ea-8229-763fc80f3b21.png)
Configuration - open states:
![Screen Shot 2019-12-13 at 7 33 20 PM](https://user-images.githubusercontent.com/2818133/70841348-73723b00-1ddf-11ea-90e3-fd0de332893f.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Props to @linawiezkowiak and @oszkarnagy for the UX/Design work.

**Comment by jeffpaul** [comment]
Good feedback from @justintadlock on [WP Tavern](https://wptavern.com/10up-releases-autoshare-for-twitter-wordpress-plugin) to better help inform our UX updates on this topic:
> The biggest downside to the plugin is there are no links, no admin help tab, and no instructions on how to set up the Twitter Credentials on the plugin’s setting screen. The page simply has some text fields for things like an API Key, API Secret, and so on. These are not user-friendly terms, and will likely be confusing for many. Not to mention, similar plugins can connect users at the click of a button. For a plugin that does nearly everything else right, this is a missing piece of what would be a near-perfect release.
>
> The plugin is ideal for power users or developers who want to set up Twitter sharing for a client. In the current version of the plugin, users need to set up a Twitter Developer account and create a Twitter App. This generates the API keys and necessary tokens for using the plugin.

**Comment by henrywright** [comment]
In a network install context, it may not be feasible to ask the individual site admin to create a new Twitter app. If the plugin could be configured in the network admin area that would be a huge improvement

**Comment by jeffpaul** [comment]
@henrywright it would seem likely thought that the individual sites would have different Twitter accounts that would need to be established though, yeah?  I mean, I can see where it's possible that all sites share the same Twitter account, but given the alternative it seems like we'd want to design for that as well?

**Comment by henrywright** [comment]
good question @jeffpaul . I think it is highly likely each _user_ will have a different Twitter handle but I think just 1 Twitter _app_ is necessary for the network

**Comment by rickalee** [comment]
Client just had a permalink with 165 characters that truncated post title. I see the 'autoshare_for_twitter_post_url' filter but I think we should add a Setting to use shortlinks i.e. example.com/?p=1234

**Comment by jeffpaul** [comment]
@rickalee using shortlinks, as an option, seems to make sense.  Though I'm surprised that Twitter itself didn't shorten the link with their t.co link shortener, I wonder if there's a way to trigger that via their API so we don't need to worry about adding a setting for that in the plugin and just let Twitter shorten things on their end?

**_Sidebar: let's move this into a separate issue to discuss link shortening._**
