### ISSUE TITLE
Escaped characters appearing in tweets

### ISSUE THREAD

**Issue by johnwatkins0** [10up/autoshare-for-twitter#72]
**Describe the bug**

Testing found escaped hyphen characters in tweets. There are likely other characters that would also be escaped.

<img width="612" alt="download (1)" src="https://user-images.githubusercontent.com/9020968/73377890-645b2580-4285-11ea-81d6-85357b3f4e8c.png">

**Steps to Reproduce**

Needs to do some local testing to determine exactly where the issue derives.

**Expected behavior**

No escaped characters should be present in auto-generated tweets.

**Comment by rickalee** [comment]
Reported by client now as well with ' 

![a3f9f3e8c07f75c57b9e09e3d1e186cf](https://user-images.githubusercontent.com/2164566/73465249-1bbb6f00-434e-11ea-8b9e-43ad9684b5bb.jpg)

**Comment by johnwatkins0** [comment]
I'm going to have a little extra time this afternoon and will look at this for 1.1.0.
