### ISSUE TITLE
Handling of shortlinks

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#88]
**Describe the bug**
Originally reported by @rickalee: https://github.com/10up/autoshare-for-twitter/issues/57#issuecomment-589209740
> Client just had a permalink with 165 characters that truncated post title. I see the 'autoshare_for_twitter_post_url' filter but I think we should add a Setting to use shortlinks i.e. example.com/?p=1234

Original response by @jeffpaul: https://github.com/10up/autoshare-for-twitter/issues/57#issuecomment-589222260
> @rickalee using shortlinks, as an option, seems to make sense. Though I'm surprised that Twitter itself didn't shorten the link with their t.co link shortener, I wonder if there's a way to trigger that via their API so we don't need to worry about adding a setting for that in the plugin and just let Twitter shorten things on their end?
> 
> **Sidebar: let's move this into a separate issue to discuss link shortening.**

**Steps to Reproduce**

**Expected behavior**

If a link to the post/page/whatever is included in our tweet [status](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update), then my assumption is those links (if they're longer than the t.co links) will be shortened to the [t.co link](https://developer.twitter.com/en/docs/basics/tco) when posted to Twitter.

**Screenshots**

n/a

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

Related to #57

**Comment by jeffpaul** [comment]
@rickalee let's pick up conversation on your shortlink bug/needs here; please provide a little more clarity on the issue you're seeing as my assumption is that t.co links should resolve any issues with links truncating status messages when posted to Twitter.

**Comment by iamdharmesh** [comment]
This could be fixed by https://github.com/10up/autoshare-for-twitter/pull/288
