### ISSUE TITLE
Add acceptance tests

### ISSUE THREAD

**Issue by jeffpaul** [10up/autoshare-for-twitter#91]
**Is your enhancement related to a problem? Please describe.**
As a follow on from #84, let's look to get acceptance tests to cover these two scenarios while similarly working to figure out why they occasionally fail in manual testing.

**Describe the solution you'd like**
- [ ] A test that checked the autoshare box, saved the draft, unchecked the autoshare box, published the post, and verified no tweet was sent
- [ ] A test that saved a draft with the autoshare box unchecked, checked the box on the following pageload, published the post, and verified that the tweet was sent

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by thrijith** [comment]
Hi @jeffpaul, I'd like to take this if available, thanks!

**Comment by dinhtungdu** [comment]
hi @thrijith, please note that WPAcceptance isn't working now, there is a fix in review to fix this https://github.com/10up/wpacceptance/pull/34

**Comment by thrijith** [comment]
@jeffpaul based on https://github.com/10up/autoshare-for-twitter/pull/120#issuecomment-912584278, wanted to check if I should hold this now.

**Comment by jeffpaul** [comment]
@thrijith yes, though you can ping @dinhtungdu and @Sidsector9 as https://github.com/10up/simple-podcasting has been updated to the new e2e testing approach and https://github.com/10up/restricted-site-access will also be soon.  You could mimic what is done there for this plugin.

**Comment by thrijith** [comment]
@dinhtungdu I have started on adding cypress tests, how can I pass demo app credentials securely here https://github.com/10up/autoshare-for-twitter/blob/feature/add-cypress-tests/tests/cypress/integration/admin.test.js#L28 ?

**Comment by dinhtungdu** [comment]
@thrijith IMO we can:
- Skip testing parts that communicate with the Twitter server to only test our plugin, not the communication with Twitter APIs.
- Or we can pass the credentials to GitHub Actions using [Environment variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables).

**Comment by thrijith** [comment]
Hi @jeffpaul @dinhtungdu 

- I've added the existing test in wpacceptance to the cypress setup along with new test cases to check the points mentioned in this issues description.

- The tests are now passing on https://github.com/10up/autoshare-for-twitter/pull/145, please review when you get a chance.

- As we are using twitter creds via Github secrets, we can verify if tweet feature is working as expected too, I am using this demo account for now https://twitter.com/gh_issue_help
