### ISSUE TITLE
Test workflow should run in more situations

### ISSUE THREAD

**Issue by johnwatkins0** [10up/autoshare-for-twitter#95]
**Is your enhancement related to a problem? Please describe.**

Currently the test workflow only runs on PRs to `develop`. This came up when I was releasing 1.0.2. After merging `develop` into `master` it would have been ideal to have the tests run at that point, before `master` was merged to `stable`. I was able to simulate the test workflow on the `master` branch locally, but it should be automated. 

**Describe the solution you'd like**

The test workflow should run on commits to master. There may be other times when it should run as well.

**Comment by jeffpaul** [comment]
@johnwatkins0 I _think_ it should be as straightforward as adding `- master` (and for that matter `- stable` if we wanted) after the `- develop` line here, yeah?
https://github.com/10up/autoshare-for-twitter/blob/cf70840b7d4ebe290ad46de84baf249e96ce17c1/.github/workflows/test.yml#L6
